server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_gallery?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ai_admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大限制
      max-request-size: 50MB   # 单次请求总大小限制

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置
file:
  upload-dir: D:/vscode/AI_Gallery/uploads/

# 阿里云 DashScope 配置
aliyun:
  dashscope:
    api-key: sk-6bbf5eaf65c84bfe85556832f339c71c

# 高德地图配置
amap:
  web-service:
    key: 1eb04750b7f55f92385ded2cf143ea70

# 百度 AI 图片识别配置
baidu:
  ai:
    app-id: 121117508
    api-key: wRdtMM5oyZA7ElnCXTd8WR6N
    secret-key: pPvK7TUIAyQ2rQza8Bgxin9lHfibDDfj