server:
  port: 8080 # ???? 8080 ??

spring:
  datasource:
    # ????????
    url: jdbc:mysql://localhost:3306/ai_gallery?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    # ??????????????
    username: ai_admin
    # ??????????????
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# ?????? SQL ????????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl