server:
  port: 8080 # ???? 8080 ??

spring:
  datasource:
    # ??? ai_gallery ??????????
    url: jdbc:mysql://localhost:3306/ai_gallery?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    # ????????????????? MySQL ???
    password: 060122
    driver-class-name: com.mysql.cj.jdbc.Driver

# ?????? SQL ????????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl